# Generated by Django 5.2.14 on 2026-07-03 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenterAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_code', models.CharField(blank=True, default='', max_length=80)),
                ('platform_label', models.CharField(blank=True, default='', max_length=160)),
                ('account_id', models.CharField(blank=True, default='', max_length=80)),
                ('account_label', models.CharField(blank=True, default='', max_length=255)),
                ('days', models.PositiveIntegerField(default=30)),
                ('status_filter', models.CharField(blank=True, default='ACTIVE', max_length=40)),
                ('score', models.PositiveIntegerField(default=0)),
                ('score_delta', models.IntegerField(default=0)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('measured_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, default='openai', max_length=30)),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('agents_payload', models.JSONField(blank=True, default=list)),
                ('decision_notes', models.JSONField(blank=True, default=list)),
                ('metrics_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_center_ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reklam Sağlık Merkezi AI Analizi',
                'verbose_name_plural': 'Reklam Sağlık Merkezi AI Analizleri',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_health_user_id_5a9350_idx'), models.Index(fields=['user', 'platform_code', 'account_id', '-created_at'], name='core_health_user_id_29e062_idx')],
            },
        ),
    ]
