# Generated by Django 5.2.14 on 2026-07-05 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthcenteraianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('frequency', models.CharField(choices=[('daily', 'Gunluk'), ('weekly', 'Haftalik'), ('biweekly', '15 Gunluk'), ('monthly', 'Aylik')], default='weekly', max_length=20)),
                ('recipient_emails', models.JSONField(blank=True, default=list)),
                ('include_campaign_summary', models.BooleanField(default=True)),
                ('include_ad_performance', models.BooleanField(default=True)),
                ('include_rule_recommendations', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_hour', models.PositiveSmallIntegerField(default=9)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='scheduled_reports', to='core.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Otomatik Rapor',
                'verbose_name_plural': 'Otomatik Raporlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_schedu_user_id_ba2c27_idx'), models.Index(fields=['next_run_at'], name='core_schedu_next_ru_fafa89_idx')],
            },
        ),
    ]
