# Generated by Django 5.2.14 on 2026-07-05 13:02

import core.models.membership
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scheduledreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models.membership.generate_referral_code, max_length=40, unique=True, verbose_name='Promosyon kodu')),
                ('reward_type', models.CharField(choices=[('ai_credits', 'AI kredi'), ('subscription_days', 'Abonelik günü')], default='ai_credits', max_length=30, verbose_name='Ödül tipi')),
                ('reward_amount', models.PositiveIntegerField(default=10000, verbose_name='Ödül miktarı')),
                ('description', models.CharField(blank=True, default='', max_length=180, verbose_name='Açıklama')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam kullanım limiti')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Son geçerlilik tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL, verbose_name='Kod sahibi')),
            ],
            options={
                'verbose_name': 'Referans / Promosyon Kodu',
                'verbose_name_plural': 'Referans / Promosyon Kodları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('ai_credits', 'AI kredi'), ('subscription_days', 'Abonelik günü')], max_length=30, verbose_name='Ödül tipi')),
                ('reward_amount', models.PositiveIntegerField(default=0, verbose_name='Ödül miktarı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('awarded', 'Hak tanımlandı'), ('cancelled', 'İptal')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('awarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Hak tanımlama zamanı')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to='core.payment')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='core.referralcode', verbose_name='Promosyon kodu')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_triggered', to=settings.AUTH_USER_MODEL, verbose_name='Abone olan üye')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_earned', to=settings.AUTH_USER_MODEL, verbose_name='Hak sahibi')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to='core.usersubscription')),
            ],
            options={
                'verbose_name': 'Referans Ödülü',
                'verbose_name_plural': 'Referans Ödülleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='core_referr_code_bb15e0_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['owner', 'is_active'], name='core_referr_owner_i_9ba240_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['referrer', 'status', '-created_at'], name='core_referr_referre_b41c08_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['referred_user', '-created_at'], name='core_referr_referre_ace4d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralreward',
            constraint=models.UniqueConstraint(fields=('referral_code', 'referred_user'), name='uniq_referral_reward_code_user'),
        ),
    ]
