# Generated by Django 5.2.14 on 2026-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_referral_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=40, unique=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Referans/promosyon sistemi aktif')),
                ('default_reward_type', models.CharField(choices=[('ai_credits', 'AI kredi'), ('subscription_days', 'Abonelik günü')], default='ai_credits', max_length=30, verbose_name='Varsayılan ödül tipi')),
                ('default_reward_amount', models.PositiveIntegerField(default=10000, verbose_name='Varsayılan ödül miktarı')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referans Program Ayarı',
                'verbose_name_plural': 'Referans Program Ayarı',
            },
        ),
    ]
