# Generated by Django 5.2.14 on 2026-07-06 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_referral_program_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referralreward',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment',), name='uniq_referral_reward_payment'),
        ),
    ]
