# Generated by Django 5.2.14 on 2026-07-06 07:24

from decimal import Decimal
from django.db import migrations, models


def create_default_referral_rules(apps, schema_editor):
    ReferralProgramRule = apps.get_model("core", "ReferralProgramRule")
    rows = [
        {
            "name": "Isletme aylik referans kurali",
            "plan_type": "business",
            "billing_period": "monthly",
            "new_customer_discount_percent": Decimal("10.00"),
            "reward_type": "ai_credits",
            "reward_amount": 10000,
            "priority": 10,
            "is_active": True,
        },
        {
            "name": "Isletme yillik referans kurali",
            "plan_type": "business",
            "billing_period": "yearly",
            "new_customer_discount_percent": Decimal("10.00"),
            "reward_type": "ai_credits",
            "reward_amount": 20000,
            "priority": 10,
            "is_active": True,
        },
        {
            "name": "Ajans aylik referans kurali",
            "plan_type": "agency",
            "billing_period": "monthly",
            "new_customer_discount_percent": Decimal("10.00"),
            "reward_type": "ai_credits",
            "reward_amount": 25000,
            "priority": 10,
            "is_active": True,
        },
        {
            "name": "Ajans yillik referans kurali",
            "plan_type": "agency",
            "billing_period": "yearly",
            "new_customer_discount_percent": Decimal("10.00"),
            "reward_type": "ai_credits",
            "reward_amount": 50000,
            "priority": 10,
            "is_active": True,
        },
    ]
    for row in rows:
        defaults = row.copy()
        name = defaults.pop("name")
        ReferralProgramRule.objects.update_or_create(name=name, defaults=defaults)


def remove_default_referral_rules(apps, schema_editor):
    ReferralProgramRule = apps.get_model("core", "ReferralProgramRule")
    ReferralProgramRule.objects.filter(
        name__in=[
            "Isletme aylik referans kurali",
            "Isletme yillik referans kurali",
            "Ajans aylik referans kurali",
            "Ajans yillik referans kurali",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_referral_abuse_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralprogramsetting',
            name='agency_reward_ai_credits',
            field=models.PositiveIntegerField(default=25000, verbose_name='Ajans planı ödül kredisi'),
        ),
        migrations.AddField(
            model_name='referralprogramsetting',
            name='business_reward_ai_credits',
            field=models.PositiveIntegerField(default=10000, verbose_name='İşletme planı ödül kredisi'),
        ),
        migrations.AddField(
            model_name='referralprogramsetting',
            name='new_customer_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Yeni üye indirim yüzdesi'),
        ),
        migrations.AddField(
            model_name='referralprogramsetting',
            name='yearly_reward_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Yıllık abonelik ödül çarpanı'),
        ),
        migrations.CreateModel(
            name='ReferralProgramRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kural adı')),
                ('plan_type', models.CharField(choices=[('any', 'Tüm plan tipleri'), ('business', 'İşletme'), ('agency', 'Ajans')], db_index=True, default='any', max_length=20, verbose_name='Plan tipi')),
                ('billing_period', models.CharField(choices=[('any', 'Tüm dönemler'), ('monthly', 'Aylık'), ('yearly', 'Yıllık')], db_index=True, default='any', max_length=20, verbose_name='Faturalama dönemi')),
                ('new_customer_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Yeni üye indirim yüzdesi')),
                ('reward_type', models.CharField(choices=[('ai_credits', 'AI kredi'), ('subscription_days', 'Abonelik günü')], default='ai_credits', max_length=30, verbose_name='Ödül tipi')),
                ('reward_amount', models.PositiveIntegerField(default=10000, verbose_name='Öneren üye ödül miktarı')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='Öncelik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referans Program Kuralı',
                'verbose_name_plural': 'Referans Program Kuralları',
                'ordering': ['priority', 'plan_type', 'billing_period', 'name'],
                'indexes': [models.Index(fields=['is_active', 'plan_type', 'billing_period', 'priority'], name='core_referr_is_acti_e0e03e_idx')],
            },
        ),
        migrations.RunPython(create_default_referral_rules, remove_default_referral_rules),
    ]
