# Generated by Django 5.2.14 on 2026-07-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_referral_program_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='monthly', max_length=20, verbose_name='Faturalama dönemi'),
        ),
    ]
