# Generated by Django 5.2.14 on 2026-07-06 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_billing_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('company', models.CharField(max_length=180, verbose_name='Firma / Marka')),
                ('role', models.CharField(blank=True, default='', max_length=120, verbose_name='Rol')),
                ('ad_spend', models.CharField(blank=True, default='', max_length=120, verbose_name='Aylık reklam bütçesi')),
                ('platforms', models.JSONField(blank=True, default=list, verbose_name='İlgilendiği alanlar')),
                ('goal', models.CharField(max_length=220, verbose_name='Öncelikli hedef')),
                ('message', models.TextField(blank=True, default='', verbose_name='Ek not')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='İlgilenme zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_demo_requests', to=settings.AUTH_USER_MODEL, verbose_name='İlgilenen admin')),
            ],
            options={
                'verbose_name': 'Demo Talebi',
                'verbose_name_plural': 'Demo Talepleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='core_demore_is_read_4554b9_idx'), models.Index(fields=['email', '-created_at'], name='core_demore_email_2586ec_idx')],
            },
        ),
    ]
