# Generated by Django 5.2.14 on 2026-07-14 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_turkish_only_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Duyuru başlığı')),
                ('message', models.TextField(verbose_name='Duyuru metni')),
                ('link', models.URLField(blank=True, default='', verbose_name='Bağlantı')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın zamanı')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş zamanı')),
                ('send_in_app', models.BooleanField(default=True, verbose_name='Panel bildirimi gönder')),
                ('send_email', models.BooleanField(default=False, verbose_name='E-posta gönder')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genel Duyuru',
                'verbose_name_plural': 'Genel Duyurular',
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='14 gün sonrası abonelik hatırlatması', max_length=160)),
                ('subject', models.CharField(default='Reklam performansınızı birlikte büyütelim', max_length=200)),
                ('body', models.TextField(default='14 günlük deneyiminiz sona erdi. Reklam verilerinizi tek panelde izlemeye ve Octo önerilerinden yararlanmaya devam etmek için size uygun paketi seçebilirsiniz.\n\nSorunuz olursa yanıtlamaktan memnuniyet duyarız.')),
                ('cta_text', models.CharField(default='Paketleri İncele', max_length=80)),
                ('cta_url', models.URLField(default='https://reklamanaliz.net/pricing/')),
                ('delay_days', models.PositiveSmallIntegerField(default=14, help_text='Üyelik başlangıcından kaç gün sonra ilk e-posta gönderilsin?')),
                ('repeat_days', models.PositiveSmallIntegerField(default=7, help_text='Abone olunmadıysa kaç günde bir tekrar gönderilsin?')),
                ('max_sends', models.PositiveSmallIntegerField(default=3, help_text='Bir kullanıcıya en fazla kaç kez gönderilsin?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abonelik Takip E-postası',
                'verbose_name_plural': 'Abonelik Takip E-postaları',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_created', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duyuru Teslimatı',
                'verbose_name_plural': 'Duyuru Teslimatları',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_announcement_delivery')],
            },
        ),
        migrations.CreateModel(
            name='LifecycleEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('sent', 'Gönderildi'), ('failed', 'Başarısız')], max_length=20)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.lifecycleemailcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Takip E-postası Gönderimi',
                'verbose_name_plural': 'Takip E-postası Gönderimleri',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user', 'sequence'), name='uniq_lifecycle_email_delivery')],
            },
        ),
    ]
