# Generated by Django 5.2.14 on 2026-07-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_email_html_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ai_credit_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.aicreditpackage'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_research_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.productresearchpackage'),
        ),
    ]
