# Generated by Django 5.2.14 on 2026-07-16 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_legal_documents(apps, schema_editor):
    from core.legal_defaults import LEGAL_DOCUMENTS

    LegalSiteSettings = apps.get_model('core', 'LegalSiteSettings')
    LegalDocument = apps.get_model('core', 'LegalDocument')
    LegalSiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            'company_name': 'HZR Yazılım Danışmanlık Dijital Paz. LTD ŞTİ',
            'brand_name': 'ReklamAnaliz.net',
            'address': 'Bakırköy',
            'support_email': 'info@reklamanaliz.net',
            'kvkk_email': 'info@reklamanaliz.net',
            'sla_target': 99.50,
        },
    )
    for order, document in enumerate(LEGAL_DOCUMENTS, start=10):
        defaults = dict(document)
        slug = defaults.pop('slug')
        defaults.update({'status': 'draft', 'version': '1.0', 'display_order': order * 10})
        LegalDocument.objects.update_or_create(slug=slug, defaults=defaults)


def unseed_legal_documents(apps, schema_editor):
    from core.legal_defaults import LEGAL_DOCUMENTS

    LegalDocument = apps.get_model('core', 'LegalDocument')
    slugs = [document['slug'] for document in LEGAL_DOCUMENTS]
    LegalDocument.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_payment_addon_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=240, verbose_name='Resmi şirket unvanı')),
                ('brand_name', models.CharField(default='ReklamAnaliz.net', max_length=120, verbose_name='Marka adı')),
                ('address', models.TextField(blank=True, default='', verbose_name='Açık adres')),
                ('tax_office', models.CharField(blank=True, default='', max_length=120, verbose_name='Vergi dairesi')),
                ('tax_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Vergi numarası')),
                ('mersis_number', models.CharField(blank=True, default='', max_length=32, verbose_name='MERSİS numarası')),
                ('kep_address', models.EmailField(blank=True, default='', max_length=254, verbose_name='KEP adresi')),
                ('support_email', models.EmailField(default='info@reklamanaliz.net', max_length=254, verbose_name='Destek e-postası')),
                ('kvkk_email', models.EmailField(default='info@reklamanaliz.net', max_length=254, verbose_name='KVKK başvuru e-postası')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefon')),
                ('sla_target', models.DecimalField(decimal_places=2, default=99.5, max_digits=5, verbose_name='Aylık SLA hedefi (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hukuki Metin Şirket Ayarı',
                'verbose_name_plural': 'Hukuki Metin Şirket Ayarları',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=220, verbose_name='Başlık')),
                ('category', models.CharField(choices=[('sales', 'Satış ve üyelik'), ('privacy', 'Gizlilik ve kişisel veriler'), ('platform', 'Platform verileri'), ('service', 'Hizmet ve güvenlik'), ('ai', 'Yapay zeka')], max_length=24, verbose_name='Kategori')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Kısa açıklama')),
                ('content', models.TextField(help_text='Başlıklar için <h2>, paragraflar için <p>, listeler için <ul><li> kullanabilirsiniz.', verbose_name='Metin (HTML)')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında'), ('archived', 'Arşiv')], db_index=True, default='draft', max_length=16)),
                ('version', models.CharField(default='1.0', max_length=24, verbose_name='Sürüm')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Yürürlük tarihi')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Yayın zamanı')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='Gösterim sırası')),
                ('requires_acceptance', models.BooleanField(default=False, verbose_name='Kullanıcı onayı gerektirir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hukuki Metin',
                'verbose_name_plural': 'Hukuki Metinler',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.RunPython(seed_legal_documents, unseed_legal_documents),
    ]
