# Generated by Django 5.2.14 on 2026-07-16 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def publish_initial_legal_documents(apps, schema_editor):
    from core.legal_defaults import LEGAL_DOCUMENTS

    LegalDocument = apps.get_model("core", "LegalDocument")
    now = django.utils.timezone.now()
    LegalDocument.objects.filter(slug__in=[item["slug"] for item in LEGAL_DOCUMENTS]).update(
        status="published",
        published_at=now,
        effective_date=now.date(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fix_default_site_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_snapshots', models.JSONField(default=list, verbose_name='Onaylanan belge kopyaları')),
                ('acceptance_statement', models.TextField(verbose_name='Onay beyanı')),
                ('immediate_service_consent', models.BooleanField(default=False, verbose_name='Hizmetin hemen başlaması onayı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresi')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='Tarayıcı bilgisi')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Onay zamanı')),
                ('email_recipient', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta alıcısı')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='E-posta gönderim zamanı')),
                ('email_error', models.TextField(blank=True, default='', verbose_name='E-posta hatası')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptance', to='core.payment', verbose_name='Ödeme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sözleşme Onayı',
                'verbose_name_plural': 'Sözleşme Onayları',
                'ordering': ('-accepted_at',),
            },
        ),
        migrations.RunPython(publish_initial_legal_documents, migrations.RunPython.noop),
    ]
