# Generated by Django 5.2.14 on 2026-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_enable_platinum_content_calendar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adgroupmetrichistory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='admetrichistory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmetrichistory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='creativemetrichistory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='adgroupmetrichistory',
            constraint=models.UniqueConstraint(fields=('ad_group', 'date'), name='uniq_adgroup_metric_date'),
        ),
        migrations.AddConstraint(
            model_name='admetrichistory',
            constraint=models.UniqueConstraint(fields=('ad', 'date'), name='uniq_ad_metric_date'),
        ),
        migrations.AddConstraint(
            model_name='campaignmetrichistory',
            constraint=models.UniqueConstraint(fields=('campaign', 'date'), name='uniq_campaign_metric_date'),
        ),
        migrations.AddConstraint(
            model_name='creativemetrichistory',
            constraint=models.UniqueConstraint(fields=('creative', 'date'), name='uniq_creative_metric_date'),
        ),
    ]
