from django.contrib.auth.decorators import login_required
from django.shortcuts import render


GLOSSARY_TERMS = [
    {"term": "ROAS", "name": "Reklam Harcaması Getirisi", "category": "Performans", "formula": "Reklam kaynaklı gelir / Reklam harcaması", "description": "Reklama yatırılan her 1 TL'nin kaç TL gelir ürettiğini gösterir.", "example": "10.000 TL gelir / 2.000 TL harcama = 5,0 ROAS", "aliases": "return on ad spend gelir reklam getirisi"},
    {"term": "ROI", "name": "Yatırım Getirisi", "category": "Performans", "formula": "(Kazanç - Toplam maliyet) / Toplam maliyet × 100", "description": "Reklam dışındaki maliyetleri de hesaba katarak yatırımın net kârlılığını ölçer.", "example": "15.000 TL kazanç, 10.000 TL maliyet = %50 ROI", "aliases": "return on investment yatırım karlılık"},
    {"term": "MER", "name": "Pazarlama Verimlilik Oranı", "category": "Performans", "formula": "Toplam gelir / Toplam pazarlama harcaması", "description": "Tek bir platform yerine bütün pazarlama faaliyetlerinin toplam verimini gösterir.", "example": "500.000 TL toplam gelir / 100.000 TL pazarlama = 5,0 MER", "aliases": "marketing efficiency ratio blended roas toplam roas"},
    {"term": "CTR", "name": "Tıklama Oranı", "category": "Performans", "formula": "Tıklama / Gösterim × 100", "description": "Reklamı görenlerin yüzde kaçının tıkladığını gösterir. Kreatif ve mesaj ilgisinin temel sinyallerindendir.", "example": "500 tıklama / 20.000 gösterim = %2,5 CTR", "aliases": "click through rate tıklanma oranı crs"},
    {"term": "CVR / CR", "name": "Dönüşüm Oranı", "category": "Dönüşüm", "formula": "Dönüşüm / Ziyaret veya tıklama × 100", "description": "Siteye gelen ya da reklama tıklayan kullanıcıların hedeflenen işlemi tamamlama oranıdır.", "example": "40 satış / 1.000 ziyaret = %4 dönüşüm oranı", "aliases": "conversion rate cr cvr dönüşüm satış oranı"},
    {"term": "CPC", "name": "Tıklama Başına Maliyet", "category": "Maliyet", "formula": "Reklam harcaması / Tıklama", "description": "Her bir reklam tıklaması için ortalama ne kadar ödendiğini gösterir.", "example": "2.000 TL / 500 tıklama = 4 TL CPC", "aliases": "cost per click tıklama maliyeti"},
    {"term": "CPM", "name": "Bin Gösterim Başına Maliyet", "category": "Maliyet", "formula": "Reklam harcaması / Gösterim × 1.000", "description": "Reklamın bin kez gösterilmesinin ortalama maliyetidir.", "example": "3.000 TL / 150.000 gösterim × 1.000 = 20 TL CPM", "aliases": "cost per mille thousand impression gösterim maliyeti"},
    {"term": "CPA", "name": "Aksiyon Başına Maliyet", "category": "Maliyet", "formula": "Reklam harcaması / Dönüşüm", "description": "Satın alma, kayıt veya form doldurma gibi hedeflenen her aksiyonun ortalama maliyetidir.", "example": "6.000 TL / 120 satış = 50 TL CPA", "aliases": "cost per action acquisition dönüşüm satış maliyeti"},
    {"term": "CPL", "name": "Potansiyel Müşteri Başına Maliyet", "category": "Maliyet", "formula": "Reklam harcaması / Lead sayısı", "description": "Her bir form, teklif talebi veya potansiyel müşteri kaydının maliyetidir.", "example": "4.000 TL / 80 lead = 50 TL CPL", "aliases": "cost per lead form teklif müşteri adayı"},
    {"term": "CAC", "name": "Müşteri Edinme Maliyeti", "category": "Maliyet", "formula": "Toplam satış ve pazarlama maliyeti / Yeni müşteri", "description": "Yeni ve ödeme yapan bir müşteriyi kazanmanın toplam maliyetidir.", "example": "100.000 TL / 500 yeni müşteri = 200 TL CAC", "aliases": "customer acquisition cost müşteri kazanım maliyeti"},
    {"term": "CPI", "name": "Uygulama Yükleme Başına Maliyet", "category": "Maliyet", "formula": "Reklam harcaması / Uygulama yükleme", "description": "Mobil uygulamanın her yeni kurulumu için oluşan ortalama reklam maliyetidir.", "example": "10.000 TL / 2.000 yükleme = 5 TL CPI", "aliases": "cost per install app uygulama indirme"},
    {"term": "CPV", "name": "Video İzleme Başına Maliyet", "category": "Maliyet", "formula": "Video reklam harcaması / Ücretlendirilen izleme", "description": "Platformun izleme kriterini karşılayan her video görüntülemesinin maliyetidir.", "example": "1.500 TL / 7.500 izleme = 0,20 TL CPV", "aliases": "cost per view video görüntüleme maliyeti"},
    {"term": "CPE", "name": "Etkileşim Başına Maliyet", "category": "Maliyet", "formula": "Reklam harcaması / Etkileşim", "description": "Beğeni, yorum, paylaşım veya kaydetme gibi her etkileşimin ortalama maliyetidir.", "example": "2.000 TL / 4.000 etkileşim = 0,50 TL CPE", "aliases": "cost per engagement beğeni yorum paylaşım"},
    {"term": "AOV", "name": "Ortalama Sipariş Tutarı", "category": "E-ticaret", "formula": "Toplam sipariş geliri / Sipariş sayısı", "description": "Bir müşterinin tek siparişte ortalama ne kadar harcadığını gösterir.", "example": "120.000 TL / 400 sipariş = 300 TL AOV", "aliases": "average order value sepet ortalaması"},
    {"term": "LTV / CLV", "name": "Müşteri Yaşam Boyu Değeri", "category": "E-ticaret", "formula": "Ortalama sipariş × Satın alma sıklığı × Müşteri ömrü", "description": "Bir müşterinin işletmeyle ilişkisi boyunca sağlayacağı tahmini toplam değerdir.", "example": "500 TL × yılda 4 sipariş × 3 yıl = 6.000 TL LTV", "aliases": "lifetime value customer lifetime value yaşam boyu değer"},
    {"term": "Sepete Ekleme Oranı", "name": "Add to Cart Rate", "category": "E-ticaret", "formula": "Sepete ekleme / Ürün sayfası ziyareti × 100", "description": "Ürün sayfasını görenlerin ürünü sepete ekleme oranıdır.", "example": "150 sepete ekleme / 2.000 ziyaret = %7,5", "aliases": "atc add to cart cart rate sepet"},
    {"term": "Sepet Terk Oranı", "name": "Cart Abandonment Rate", "category": "E-ticaret", "formula": "(Sepet - Satın alma) / Sepet × 100", "description": "Sepete ürün eklediği hâlde satın almayı tamamlamayan kullanıcıların oranıdır.", "example": "200 sepet, 60 sipariş = %70 terk oranı", "aliases": "abandoned cart checkout terk"},
    {"term": "Başabaş ROAS", "name": "Break-even ROAS", "category": "E-ticaret", "formula": "1 / Brüt kâr marjı", "description": "Reklamın zarar etmemesi için ulaşması gereken minimum ROAS değeridir. Diğer işletme giderleri ayrıca değerlendirilmelidir.", "example": "%40 brüt marj için 1 / 0,40 = 2,5 ROAS", "aliases": "breakeven başa baş karlılık marj"},
    {"term": "Gösterim", "name": "Impression", "category": "Erişim", "formula": "Reklamın ekranda gösterildiği toplam sayı", "description": "Aynı kişi birden fazla kez gördüğünde her gösterim ayrı sayılır.", "example": "10.000 kişiye toplam 18.000 gösterim yapılabilir.", "aliases": "impressions gösterilme"},
    {"term": "Erişim", "name": "Reach", "category": "Erişim", "formula": "Reklamı gören tekil kişi veya hesap sayısı", "description": "Gösterimden farklı olarak aynı kullanıcı yalnızca bir kez sayılır.", "example": "18.000 gösterim 10.000 tekil kişiye ulaşmış olabilir.", "aliases": "unique reach tekil kullanıcı"},
    {"term": "Frekans", "name": "Frequency", "category": "Erişim", "formula": "Gösterim / Erişim", "description": "Bir kişinin reklamı ortalama kaç kez gördüğünü gösterir. Çok yükselmesi kreatif yorgunluğuna işaret edebilir.", "example": "18.000 gösterim / 10.000 erişim = 1,8 frekans", "aliases": "frequency tekrar gösterim sıklığı"},
    {"term": "LPV", "name": "Açılış Sayfası Görüntüleme", "category": "Dönüşüm", "formula": "Sayfa gerçekten yüklendiğinde sayılan ziyaret", "description": "Link tıklamasından daha dar bir metriktir; tıklayıp sayfa yüklenmeden çıkanları içermez.", "example": "1.000 link tıklaması, 850 LPV olabilir.", "aliases": "landing page view açılış sayfası ziyareti"},
    {"term": "Hemen Çıkma Oranı", "name": "Bounce Rate", "category": "Dönüşüm", "formula": "Etkileşimsiz oturum / Toplam oturum × 100", "description": "Kullanıcının anlamlı bir etkileşim göstermeden ayrıldığı oturumların oranıdır; GA4 tanımı klasik Analytics'ten farklıdır.", "example": "GA4'te etkileşim oranı %65 ise bounce rate %35'tir.", "aliases": "bounce rate çıkış terk etkileşimsiz"},
    {"term": "Etkileşim Oranı", "name": "Engagement Rate", "category": "Performans", "formula": "Etkileşim / Erişim veya gösterim × 100", "description": "İçeriğin beğeni, yorum, paylaşım ve kaydetme üretme gücünü ölçer. Kullanılan payda platforma göre değişebilir.", "example": "800 etkileşim / 20.000 erişim = %4", "aliases": "engagement rate beğeni yorum paylaşım kaydetme"},
    {"term": "VTR", "name": "Video İzlenme Oranı", "category": "Video ve Kreatif", "formula": "Video izleme / Video gösterimi × 100", "description": "Video reklamı görenlerin platformun tanımladığı izleme eşiğini geçme oranıdır.", "example": "4.000 izleme / 20.000 gösterim = %20 VTR", "aliases": "view through rate video izleme oranı"},
    {"term": "Hook Rate", "name": "İlk Saniyelerde Tutma Oranı", "category": "Video ve Kreatif", "formula": "3 saniye izleme / Video başlangıcı × 100", "description": "Videonun açılışının dikkati ne kadar iyi yakaladığını gösterir. Tanım platform ve rapora göre değişebilir.", "example": "6.000 üç saniye izleme / 10.000 başlangıç = %60", "aliases": "kanca oranı thumb stop ilk 3 saniye"},
    {"term": "Tamamlama Oranı", "name": "Video Completion Rate", "category": "Video ve Kreatif", "formula": "Tam izleme / Video başlangıcı × 100", "description": "Videoyu başlatan kullanıcıların yüzde kaçının sonuna kadar izlediğini gösterir.", "example": "1.200 tam izleme / 8.000 başlangıç = %15", "aliases": "vcr completion video complete yüzde 100 izleme"},
    {"term": "Kreatif Yorgunluğu", "name": "Creative Fatigue", "category": "Video ve Kreatif", "formula": "Tek bir formülü yoktur", "description": "Aynı reklamın sık gösterilmesi sonucu ilginin azalmasıdır; artan frekans, düşen CTR ve yükselen CPA birlikte izlenir.", "example": "Frekans yükselirken CTR düşüyorsa yeni kreatif test edilebilir.", "aliases": "ad fatigue reklam yorgunluğu körlüğü"},
    {"term": "A/B Testi", "name": "Split Test", "category": "Video ve Kreatif", "formula": "Tek değişkenli kontrollü karşılaştırma", "description": "Hedef kitle, görsel veya metin gibi tek bir değişkenin iki sürümünü eşit koşullarda karşılaştırır.", "example": "Aynı kitlede yalnızca başlığı farklı iki reklam test edilir.", "aliases": "split testing varyasyon deney"},
    {"term": "Atıf", "name": "Attribution", "category": "Ölçüm", "formula": "Dönüşüm kredisini temas noktalarına dağıtan model", "description": "Bir satışın hangi reklam, kanal veya temas noktasına yazılacağını belirler.", "example": "Son tıklama modeli krediyi satın almadan önceki son tıklamaya verir.", "aliases": "attribution ilişkilendirme dönüşüm kredisi"},
    {"term": "Atıf Penceresi", "name": "Attribution Window", "category": "Ölçüm", "formula": "Tıklama veya görüntüleme sonrası tanınan süre", "description": "Bir reklam etkileşiminden ne kadar süre sonra gerçekleşen dönüşümün reklama yazılacağını belirler.", "example": "7 gün tıklama penceresinde, tıklamadan 5 gün sonraki satış sayılır.", "aliases": "conversion window lookback pencere 7 gün"},
    {"term": "Pixel", "name": "Web Ölçüm Kodu", "category": "Ölçüm", "formula": "Web sitesine eklenen olay takip kodu", "description": "Sayfa görüntüleme, sepete ekleme ve satın alma gibi kullanıcı eylemlerini reklam platformuna iletir.", "example": "Meta Pixel, Purchase olayını değer ve para birimiyle gönderebilir.", "aliases": "piksel meta pixel tracking code takip kodu"},
    {"term": "CAPI", "name": "Dönüşümler API'si", "category": "Ölçüm", "formula": "Sunucudan sunucuya olay aktarımı", "description": "Tarayıcı pikseline ek olarak dönüşüm verilerini işletmenin sunucusundan reklam platformuna iletir.", "example": "Satın alma olayı hem Pixel hem CAPI ile gönderilip tekilleştirilebilir.", "aliases": "conversions api server side tracking sunucu tarafı"},
    {"term": "UTM", "name": "Kampanya Takip Parametreleri", "category": "Ölçüm", "formula": "Kaynak, araç, kampanya ve içerik etiketleri", "description": "Bağlantıya eklenen parametrelerle trafiğin hangi reklam ve kampanyadan geldiğini analiz araçlarında ayırır.", "example": "utm_source=meta&utm_medium=paid_social&utm_campaign=yaz", "aliases": "utm source medium campaign tracking url parametre"},
    {"term": "Retargeting", "name": "Yeniden Hedefleme", "category": "Kitle", "formula": "Daha önce etkileşen kullanıcı kitlesi", "description": "Siteyi ziyaret eden, video izleyen veya sepete ürün ekleyen kişilere yeniden reklam göstermedir.", "example": "Son 30 günde sepete ekleyip satın almayanlar hedeflenebilir.", "aliases": "remarketing yeniden pazarlama sıcak kitle"},
    {"term": "Lookalike", "name": "Benzer Kitle", "category": "Kitle", "formula": "Kaynak kitleye davranışsal olarak benzeyen yeni kullanıcılar", "description": "Mevcut müşterilere veya kaliteli dönüşüm yapanlara benzeyen yeni kişileri bulmak için oluşturulur.", "example": "En değerli müşterilerden %1 benzer kitle üretilebilir.", "aliases": "lal similar audience benzer hedef kitle"},
    {"term": "Funnel", "name": "Pazarlama Hunisi", "category": "Dönüşüm", "formula": "Farkındalık → İlgi → Değerlendirme → Dönüşüm", "description": "Kullanıcının markayı ilk görmesinden satın almaya kadar geçtiği aşamaları ifade eder.", "example": "Video izleyenlere ürün reklamı, sepete ekleyenlere teklif gösterilebilir.", "aliases": "huni customer journey müşteri yolculuğu tofu mofu bofu"},
    {"term": "CBO / Advantage Campaign Budget", "name": "Kampanya Bütçesi Optimizasyonu", "category": "Bütçe", "formula": "Bütçe kampanya düzeyinde dağıtılır", "description": "Platform, kampanya bütçesini reklam setleri arasında fırsata göre otomatik dağıtır.", "example": "Günlük 2.000 TL bütçe en iyi sonuç üreten reklam setine kayabilir.", "aliases": "campaign budget optimization advantage abo meta bütçe"},
    {"term": "ABO", "name": "Reklam Seti Bütçesi", "category": "Bütçe", "formula": "Her reklam setine ayrı bütçe atanır", "description": "Bütçe dağılımı platform yerine reklamveren tarafından reklam seti düzeyinde kontrol edilir.", "example": "Üç reklam setine ayrı ayrı 500 TL günlük bütçe verilir.", "aliases": "ad set budget optimization reklam seti bütçesi cbo"},
    {"term": "Öğrenme Aşaması", "name": "Learning Phase", "category": "Bütçe", "formula": "Platformun teslimatı optimize etmek için veri topladığı dönem", "description": "Yeni veya önemli ölçüde değiştirilen reklam setinin en iyi dağıtımı bulmaya çalıştığı süreçtir.", "example": "Sık bütçe ve hedefleme değişikliği öğrenme sürecini yeniden başlatabilir.", "aliases": "learning limited öğrenme sınırlı meta optimizasyon"},
    {"term": "Teklif", "name": "Bid", "category": "Bütçe", "formula": "Reklam açık artırmasında sonuç için sunulan değer", "description": "Platformun reklam gösterimi veya dönüşüm fırsatı için açık artırmaya hangi değerle katılacağını belirler.", "example": "En düşük maliyet veya maliyet üst sınırı stratejisi seçilebilir.", "aliases": "bid bidding teklif stratejisi auction açık artırma"},
]


@login_required
def fihrist(request):
    categories = sorted({item["category"] for item in GLOSSARY_TERMS})
    return render(request, "fihrist.html", {"terms": GLOSSARY_TERMS, "categories": categories})
